### ISSUE TITLE
Definir versão requerida de triagens/arangodb

### ISSUE THREAD

**Issue by vinaocruz** [helderjs/ArangoDbSilexServiceProvider#2]
Atualmente a versão mínima requerida no packagist é triagens/arangodb: dev-master

Sugestão para indicar uma versão mínima, para que possa ser viável utilizar em alguns cenários que o arangodb não pode ser definido como dev-master.

**Comment by helderjs** [comment]
Coloquei na minha lista de pendências aqui. Confesso que esse projeto anda meio abandonado.

**Comment by vinaocruz** [comment]
Estou usando ele em uma api pessoal aqui. Quero ver como ele está pra contribuir e ajudar a manter ativo.

**Comment by helderjs** [comment]
@vinaocruz Atualizei! Da uma olhada. Preciso melhorar os testes.
